id: QmUuL9e4hxJMqfgXdbnLSvkDUwN3dsoadwLEPyt1W29uhP
description: ""
tags: []
match: data
useRegex: false
encryption:
    type: AES512
    key: signal
access:
    network: all
replicas:
    min: 0
    max: 500
storage:
    size: 100MB
