id: QmaHwdstMq2ixzAQDb5QuLDbAhUGwXTPm4FjAqUUwrom4w
description: Returns pong to a ping over http
tags: []
source: .
trigger:
    type: http
    method: GET
    paths:
        - /ping
domains:
    - GeneratedDomain
execution:
    timeout: 10s
    memory: 10MB
    call: ping
